### PR TITLE
loosen Compat requirement to 0.18

### PR DESCRIPTION
**Pull request by tkelman**
since you aren't using `@compat IndexStyle` anywhere yet

### CODE REVIEW

**Comment by tkelman** [comment]
Nightly failure on mac is unrelated. I can look up how to make nightly an allowed failure if you'd like, where it will run but not make your status red

**Comment by MikaelSlevinsky** [comment]
It should just look like
```
matrix:
  allow_failures:
    - julia: nightly
    - os: osx
```
[ApproxFun](https://github.com/JuliaApproximation/ApproxFun.jl/blob/development/.travis.yml) uses this in the travis.yml file.

**Comment by MikaelSlevinsky** [comment]
By the way, @tkelman, is the failure going to be a persistent problem on OSX in v0.6?

**Comment by MikaelSlevinsky** [comment]
Oh sorry I didn't realize nightly is now 0.7.

**Comment by tkelman** [comment]
I think we fixed the buildbot issue, let's restart and see

**Comment by MikaelSlevinsky** [comment]
Great! It looks like this and the metadata PR are ready to merge.

**Comment by tkelman** [comment]
yes. @klho can you merge this? it may be worth giving @MikaelSlevinsky commit access, and enabling https://github.com/attobot/attobot to make future releases simpler

**Comment by tkelman** [comment]
no need to modify the 0.0.2 tag since I amended the requires file in the metadata pr, and it's okay for the metadata copy and the package copy at the tag sha to differ. for registered packages at a tagged version, the metadata copy takes priority

**Pull request merged**
